#############################################################################
# Makefile for building: Pong-game-school-work
# Generated by qmake (2.01a) (Qt 4.8.1) on: Thu Mar 28 23:51:43 2013
# Project:  Pong-game-school-work.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Pong-game-school-work.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iheaders -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = sources/GameStateWorker.cpp \
		sources/LoggerWorker.cpp \
		sources/PlayingArea.cpp \
		sources/PongServer.cpp \
		tests/test_playing_area.cpp moc_GameStateWorker.cpp
OBJECTS       = GameStateWorker.o \
		LoggerWorker.o \
		PlayingArea.o \
		PongServer.o \
		test_playing_area.o \
		moc_GameStateWorker.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Pong-game-school-work.pro
QMAKE_TARGET  = Pong-game-school-work
DESTDIR       = 
TARGET        = Pong-game-school-work

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Pong-game-school-work.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Pong-game-school-work.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Pong-game-school-work.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Pong-game-school-work1.0.0 || $(MKDIR) .tmp/Pong-game-school-work1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Pong-game-school-work1.0.0/ && $(COPY_FILE) --parents headers/GameState.hpp headers/GameStateWorker.hpp headers/LoggerWorker.hpp headers/PlayerState.hpp headers/PlayingArea.hpp headers/PongServer.hpp headers/PongTypes.hpp headers/SocketWorker.hpp headers/Workers.hpp .tmp/Pong-game-school-work1.0.0/ && $(COPY_FILE) --parents sources/GameStateWorker.cpp sources/LoggerWorker.cpp sources/PlayingArea.cpp sources/PongServer.cpp tests/test_playing_area.cpp .tmp/Pong-game-school-work1.0.0/ && (cd `dirname .tmp/Pong-game-school-work1.0.0` && $(TAR) Pong-game-school-work1.0.0.tar Pong-game-school-work1.0.0 && $(COMPRESS) Pong-game-school-work1.0.0.tar) && $(MOVE) `dirname .tmp/Pong-game-school-work1.0.0`/Pong-game-school-work1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Pong-game-school-work1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_GameStateWorker.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_GameStateWorker.cpp
moc_GameStateWorker.cpp: headers/PlayingArea.hpp \
		headers/PlayerState.hpp \
		headers/PongTypes.hpp \
		headers/GameState.hpp \
		headers/GameStateWorker.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) headers/GameStateWorker.hpp -o moc_GameStateWorker.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

GameStateWorker.o: sources/GameStateWorker.cpp headers/GameStateWorker.hpp \
		headers/PlayingArea.hpp \
		headers/PlayerState.hpp \
		headers/PongTypes.hpp \
		headers/GameState.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameStateWorker.o sources/GameStateWorker.cpp

LoggerWorker.o: sources/LoggerWorker.cpp headers/LoggerWorker.hpp \
		headers/PlayerState.hpp \
		headers/PongTypes.hpp \
		headers/SocketWorker.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoggerWorker.o sources/LoggerWorker.cpp

PlayingArea.o: sources/PlayingArea.cpp headers/PlayingArea.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PlayingArea.o sources/PlayingArea.cpp

PongServer.o: sources/PongServer.cpp headers/PongServer.hpp \
		headers/Workers.hpp \
		headers/GameStateWorker.hpp \
		headers/PlayingArea.hpp \
		headers/PlayerState.hpp \
		headers/PongTypes.hpp \
		headers/GameState.hpp \
		headers/LoggerWorker.hpp \
		headers/SocketWorker.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PongServer.o sources/PongServer.cpp

test_playing_area.o: tests/test_playing_area.cpp headers/PlayingArea.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test_playing_area.o tests/test_playing_area.cpp

moc_GameStateWorker.o: moc_GameStateWorker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GameStateWorker.o moc_GameStateWorker.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

